version: "3"

services:
  nginx:
    build: ./.docker/nginx
    volumes:
      - ./src:/var/www/html
    ports:
      - "127.0.0.1:8081:80"
    depends_on:
      - php

  php:
    build: ./.docker/php
    volumes:
      - ./src:/var/www/html
